services:
  webserver:
    build: .
    container_name: gym_app
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - TZ=Europe/Madrid
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${WEB_SERVER_PORT}:3000
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - .:/web
    networks:
      - gym_app-network

  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name: gym_app-mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
    - mariadb_data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - gym_app-network

  phpmyadmin:
    image: phpmyadmin:apache
    container_name: gym_app-phpmyadmin
    restart: unless-stopped
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}                        # nombre del servicio de tu MySQL
      PMA_USER: ${DB_USER}                        # opcional
      PMA_PASSWORD: ${DB_PASSWORD}                # opcional
      UPLOAD_LIMIT: 256M                          # opcional, límite de subida de archivos .sql
      BLOWFISH_SECRET: ${PMA_SECRET}              # opcional, clave de cifrado para asegurar las cookies de autenticación
    ports:
      - "9090:80"                             
    networks:
      - gym_app-network

volumes:
  mariadb_data:
    driver: local

networks:
  gym_app-network:
    driver: bridge